import {
  CheckDLLUpdates,
  GetCPUInfo,
  GetConfig,
  GetDefaultProfile,
  GetGPUInfo,
  GetGame,
  GetGames,
  GetLogo,
  GetProfile,
  GetVersion,
  HasDLLBackup,
  InstallDLL,
  LaunchGame,
  ListDLLInstallTypes,
  ListDLLVersions,
  RestoreDLLs,
  SaveConfig,
  SaveDefaultProfile,
  SaveProfile,
  ScanGames,
  UpdateDLLs,
  VKD3DHeapCompatibilityNotice
} from '../../wailsjs/go/gui/App'
import { Quit } from '../../wailsjs/runtime/runtime'

export const desktopCommands = {
  CheckDLLUpdates,
  GetCPUInfo,
  GetConfig,
  GetDefaultProfile,
  GetGPUInfo,
  GetGame,
  GetGames,
  GetLogo,
  GetProfile,
  GetVersion,
  HasDLLBackup,
  InstallDLL,
  LaunchGame,
  ListDLLInstallTypes,
  ListDLLVersions,
  RestoreDLLs,
  SaveConfig,
  SaveDefaultProfile,
  SaveProfile,
  ScanGames,
  UpdateDLLs,
  VKD3DHeapCompatibilityNotice,
  Quit
}
