// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function CheckDLLUpdates(arg1:number):Promise<Array<gui.DLLUpdateInfo>>;

export function GetCPUInfo():Promise<gui.CPUInfo>;

export function GetConfig():Promise<gui.ConfigInfo>;

export function GetGPUInfo():Promise<gui.GPUInfo>;

export function GetGame(arg1:number):Promise<gui.GameInfo>;

export function GetGames():Promise<Array<gui.GameInfo>>;

export function GetLogo():Promise<string>;

export function GetProfile(arg1:number):Promise<gui.ProfileInfo>;

export function GetVersion():Promise<string>;

export function HasDLLBackup(arg1:number):Promise<boolean>;

export function LaunchGame(arg1:number):Promise<void>;

export function RestoreDLLs(arg1:number):Promise<void>;

export function SaveConfig(arg1:gui.ConfigInfo):Promise<void>;

export function SaveProfile(arg1:number,arg2:gui.ProfileInfo):Promise<void>;

export function ScanGames():Promise<void>;

export function UpdateDLLs(arg1:number):Promise<void>;
