// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDLLUpdates(arg1) {
  return window['go']['gui']['App']['CheckDLLUpdates'](arg1);
}

export function DefaultNavState() {
  return window['go']['gui']['App']['DefaultNavState']();
}

export function GetCPUInfo() {
  return window['go']['gui']['App']['GetCPUInfo']();
}

export function GetConfig() {
  return window['go']['gui']['App']['GetConfig']();
}

export function GetDefaultProfile() {
  return window['go']['gui']['App']['GetDefaultProfile']();
}

export function GetGPUInfo() {
  return window['go']['gui']['App']['GetGPUInfo']();
}

export function GetGame(arg1) {
  return window['go']['gui']['App']['GetGame'](arg1);
}

export function GetGames() {
  return window['go']['gui']['App']['GetGames']();
}

export function GetLogo() {
  return window['go']['gui']['App']['GetLogo']();
}

export function GetNavContract() {
  return window['go']['gui']['App']['GetNavContract']();
}

export function GetProfile(arg1) {
  return window['go']['gui']['App']['GetProfile'](arg1);
}

export function GetSettingsCatalog() {
  return window['go']['gui']['App']['GetSettingsCatalog']();
}

export function GetVersion() {
  return window['go']['gui']['App']['GetVersion']();
}

export function HasDLLBackup(arg1) {
  return window['go']['gui']['App']['HasDLLBackup'](arg1);
}

export function InstallDLL(arg1, arg2, arg3) {
  return window['go']['gui']['App']['InstallDLL'](arg1, arg2, arg3);
}

export function LaunchGame(arg1) {
  return window['go']['gui']['App']['LaunchGame'](arg1);
}

export function ListDLLInstallTypes(arg1) {
  return window['go']['gui']['App']['ListDLLInstallTypes'](arg1);
}

export function ListDLLVersions(arg1) {
  return window['go']['gui']['App']['ListDLLVersions'](arg1);
}

export function NavDestinationFromHotkey(arg1) {
  return window['go']['gui']['App']['NavDestinationFromHotkey'](arg1);
}

export function NavSelectAspect(arg1, arg2) {
  return window['go']['gui']['App']['NavSelectAspect'](arg1, arg2);
}

export function NavSelectDLLSection(arg1, arg2) {
  return window['go']['gui']['App']['NavSelectDLLSection'](arg1, arg2);
}

export function NavSelectDestination(arg1, arg2) {
  return window['go']['gui']['App']['NavSelectDestination'](arg1, arg2);
}

export function NavSelectMonitorSection(arg1, arg2) {
  return window['go']['gui']['App']['NavSelectMonitorSection'](arg1, arg2);
}

export function NavSelectScope(arg1, arg2, arg3) {
  return window['go']['gui']['App']['NavSelectScope'](arg1, arg2, arg3);
}

export function NavSelectSettingsSection(arg1, arg2) {
  return window['go']['gui']['App']['NavSelectSettingsSection'](arg1, arg2);
}

export function NavSelectSubsystem(arg1, arg2) {
  return window['go']['gui']['App']['NavSelectSubsystem'](arg1, arg2);
}

export function RestoreDLLs(arg1) {
  return window['go']['gui']['App']['RestoreDLLs'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['gui']['App']['SaveConfig'](arg1);
}

export function SaveDefaultProfile(arg1) {
  return window['go']['gui']['App']['SaveDefaultProfile'](arg1);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['gui']['App']['SaveProfile'](arg1, arg2);
}

export function ScanGames() {
  return window['go']['gui']['App']['ScanGames']();
}

export function UpdateDLLs(arg1) {
  return window['go']['gui']['App']['UpdateDLLs'](arg1);
}

export function VKD3DHeapCompatibilityNotice(arg1) {
  return window['go']['gui']['App']['VKD3DHeapCompatibilityNotice'](arg1);
}
