// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {nav} from '../models';
import {settings} from '../models';

export function CheckDLLUpdates(arg1:number):Promise<Array<gui.DLLUpdateInfo>>;

export function DefaultNavState():Promise<nav.GUIState>;

export function GetCPUInfo():Promise<gui.CPUInfo>;

export function GetConfig():Promise<gui.ConfigInfo>;

export function GetDefaultProfile():Promise<gui.ProfileInfo>;

export function GetGPUInfo():Promise<gui.GPUInfo>;

export function GetGame(arg1:number):Promise<gui.GameInfo>;

export function GetGames():Promise<Array<gui.GameInfo>>;

export function GetLogo():Promise<string>;

export function GetNavContract():Promise<nav.GUIContract>;

export function GetProfile(arg1:number):Promise<gui.ProfileInfo>;

export function GetSettingsCatalog():Promise<Array<settings.CatalogSection>>;

export function GetVersion():Promise<string>;

export function HasDLLBackup(arg1:number):Promise<boolean>;

export function InstallDLL(arg1:number,arg2:string,arg3:string):Promise<void>;

export function LaunchGame(arg1:number):Promise<void>;

export function ListDLLInstallTypes(arg1:number):Promise<Array<string>>;

export function ListDLLVersions(arg1:string):Promise<Array<string>>;

export function NavDestinationFromHotkey(arg1:string):Promise<number|boolean>;

export function NavSelectAspect(arg1:nav.GUIState,arg2:number):Promise<nav.GUIState>;

export function NavSelectDLLSection(arg1:nav.GUIState,arg2:number):Promise<nav.GUIState>;

export function NavSelectDestination(arg1:nav.GUIState,arg2:number):Promise<nav.GUIState>;

export function NavSelectMonitorSection(arg1:nav.GUIState,arg2:number):Promise<nav.GUIState>;

export function NavSelectScope(arg1:nav.GUIState,arg2:boolean,arg3:string):Promise<nav.GUIState>;

export function NavSelectSettingsSection(arg1:nav.GUIState,arg2:number):Promise<nav.GUIState>;

export function NavSelectSubsystem(arg1:nav.GUIState,arg2:number):Promise<nav.GUIState>;

export function RestoreDLLs(arg1:number):Promise<void>;

export function SaveConfig(arg1:gui.ConfigInfo):Promise<void>;

export function SaveDefaultProfile(arg1:gui.ProfileInfo):Promise<void>;

export function SaveProfile(arg1:number,arg2:gui.ProfileInfo):Promise<void>;

export function ScanGames():Promise<void>;

export function UpdateDLLs(arg1:number):Promise<void>;

export function VKD3DHeapCompatibilityNotice(arg1:number):Promise<string>;
