version: "2"

run:
  skip-dirs:
    - gui

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jgabor/spela
