package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jgabor/spela/internal/nav"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: gen-nav-js <output.js>")
		os.Exit(1)
	}

	out := filepath.Clean(os.Args[1])
	if err := os.WriteFile(out, []byte(generate()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() string {
	contract := nav.WailsContract()
	defaultState := nav.DefaultGUIState()
	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-nav-js; DO NOT EDIT.\n\n")
	b.WriteString("export const Destination = {\n")
	for _, name := range sortedKeys(contract.Destination) {
		value := contract.Destination[name]
		fmt.Fprintf(&b, "  %s: %d,\n", name, value)
	}
	b.WriteString("}\n\n")
	b.WriteString("export const Aspect = {\n")
	for _, name := range sortedKeys(contract.Aspect) {
		value := contract.Aspect[name]
		fmt.Fprintf(&b, "  %s: %d,\n", name, value)
	}
	b.WriteString("}\n\n")
	writeArray(&b, "DestinationLabels", contract.DestinationLabels)
	writeArray(&b, "AspectLabels", contract.AspectLabels)
	writeArray(&b, "ProfileSubsystemLabels", contract.ProfileSubsystemLabels)
	writeArray(&b, "SettingsSectionLabels", contract.SettingsSectionLabels)
	writeArray(&b, "MonitorSectionLabels", contract.MonitorSectionLabels)
	writeArray(&b, "DLLCatalogSectionLabels", contract.DLLCatalogSectionLabels)

	b.WriteString("\nexport function destinationFromHotkey(key) {\n")
	b.WriteString("  switch (key) {\n")
	for _, item := range []struct {
		key         string
		destination nav.Destination
	}{
		{"1", nav.DestinationLibrary},
		{"2", nav.DestinationDLLCatalog},
		{"3", nav.DestinationMonitor},
		{"4", nav.DestinationSettings},
	} {
		fmt.Fprintf(&b, "    case '%s':\n      return Destination.%s\n", item.key, destinationName(item.destination))
	}
	b.WriteString("    default:\n      return null\n  }\n}\n\n")

	b.WriteString("export function initialNavState() {\n")
	fmt.Fprintf(&b, "  return %s\n}\n", jsObject(defaultState))
	b.WriteString("\n")

	return b.String()
}

func sortedKeys(values map[string]int) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func destinationName(d nav.Destination) string {
	switch d {
	case nav.DestinationLibrary:
		return "Library"
	case nav.DestinationDLLCatalog:
		return "DLLCatalog"
	case nav.DestinationMonitor:
		return "Monitor"
	case nav.DestinationSettings:
		return "Settings"
	default:
		return "Library"
	}
}

func writeArray(b *strings.Builder, name string, values []string) {
	fmt.Fprintf(b, "export const %s = [", name)
	for i, value := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%q", value)
	}
	b.WriteString("]\n\n")
}

func jsObject(state nav.GUIState) string {
	parts := []string{
		fmt.Sprintf("destination: %d", state.Destination),
		fmt.Sprintf("scopeGlobal: %t", state.ScopeGlobal),
		fmt.Sprintf("gameName: %q", state.GameName),
		fmt.Sprintf("aspect: %d", state.Aspect),
		fmt.Sprintf("subsystem: %d", state.Subsystem),
		fmt.Sprintf("dllSection: %d", state.DLLSection),
		fmt.Sprintf("monitorSection: %d", state.MonitorSection),
		fmt.Sprintf("settingsSection: %d", state.SettingsSection),
		fmt.Sprintf("breadcrumb: [%s]", jsStringArray(state.Breadcrumb)),
	}
	return "{\n    " + strings.Join(parts, ",\n    ") + "\n  }"
}

func jsStringArray(values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = fmt.Sprintf("%q", value)
	}
	return strings.Join(quoted, ", ")
}
