// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDLLUpdates(arg1:number):Promise<Array<main.DLLUpdateInfo>>;

export function GetCPUInfo():Promise<main.CPUInfo>;

export function GetGPUInfo():Promise<main.GPUInfo>;

export function GetGame(arg1:number):Promise<main.GameInfo>;

export function GetGames():Promise<Array<main.GameInfo>>;

export function GetProfile(arg1:number):Promise<main.ProfileInfo>;

export function HasDLLBackup(arg1:number):Promise<boolean>;

export function LaunchGame(arg1:number):Promise<void>;

export function RestoreDLLs(arg1:number):Promise<void>;

export function SaveProfile(arg1:number,arg2:main.ProfileInfo):Promise<void>;

export function ScanGames():Promise<void>;

export function UpdateDLLs(arg1:number):Promise<void>;
