// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUInfo() {
  return window['go']['main']['App']['GetCPUInfo']();
}

export function GetGPUInfo() {
  return window['go']['main']['App']['GetGPUInfo']();
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function ScanGames() {
  return window['go']['main']['App']['ScanGames']();
}
